.\" Process this file with
.\" groff -man -Tascii blerp.1
.\"
.TH blerp 1 "June 2016" "xkcd" "xkcd #1692: Man Page"
.SH NAME
blerp
.SH SYNOPSIS
.B blerp
{[OPTION | ARGS] ... [ARGS ... -F [FLAGS] ...}
.br
.B blerp
{... DIRECTORY ... URL | BLERP} OPTIONS] - {}
.SH DESCRIPTION
.B blerp
filters local or remote files or resources using patterns defined by arguments and environment variables. This behavior can be altered by various flags.
.SH OPTIONS
.br
.B -a\t
Attack mode
.br
.B -b\t
Suppress bees
.br
.B -\(em\t
Flags use em dashes
.br
.B -c\t
Count number of arguments
.br
.B -d\t
Pipes output to debug.exe
.br
.B -D\t
Deprecated
.br
.B -e\t
Execute something
.br
.B -f\t
Fun mode
.br
.B -g\t
Use Google
.br
.B -h\t
Check whether input halts
.br
.B -i\t
Ignore case (lower)
.br
.B -I\t
Ignore case (upper)
.br
.B -jk\t
Kidding
.br
.B -n\t
Behavior not defined
.br
.B -o\t
Overwrite
.br
.B -O\t
Opposite day
.br
.B -p\t
Set true Pope; accepts "Rome" or "Avignon"
.br
.B -q\t
Quiet mode; output is printed to stdout instead of
.br
      being spoken aloud
.br
.B -r\t
Randomize arguments
.br
.B -R\t
Run recursively on http://*
.br
.B -s\t
Follow symbolic links symbolically
.br
.B -S\t
Stealth mode
.br
.B -t\t
Tumble dry
.br
.B -u\t
UTF-8 mode; otherwise defaults to ANSEL
.br
.B -U\t
Update (default: Facebook)
.br
.B -v\t
Verbose; alias to find / -exec cat {}
.br
.B -V\t
Set version number
.br
.B -y\t
Yikes

.SH "SEE ALSO"
.BR blerp (1),
.BR blerp (5),
.BR blirb (8),
.BR blarb (51),
.BR blorp (501)(c)(3)
.SH BUG REPORTS
http://www.inaturalist.org/taxa/47744-Hemiptera
.SH COPYRIGHT
GPL(2)(3+) CC-BY/5.0 RV 41.0 like Gecko/BSD 4(2) or best offer
